"use strict";
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");
function toast(m,t="info"){let x=$("#toast");if(!x){x=document.createElement("div");x.id="toast";x.className="toast";document.body.appendChild(x)}x.textContent=m;x.dataset.type=t;x.classList.add("show");clearTimeout(window.__t);window.__t=setTimeout(()=>x.classList.remove("show"),2500)}
function go(p,q={}){let s=new URLSearchParams(q).toString();location.href=p+(s?"?"+s:"")}
function param(k){return new URLSearchParams(location.search).get(k)||""}
function dateText(v){if(!v)return"—";try{let d=v.toDate?v.toDate():new Date(v);return d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}catch{return"—"}}
async function uploadFile(f,folder){if(!storage)throw Error("Firebase Storage is not available.");let n=f.name.replace(/[^a-zA-Z0-9._-]/g,"_");let r=storage.ref().child(folder+"/"+Date.now()+"_"+n);let s=await r.put(f);return s.ref.getDownloadURL()}
async function requireAdmin(){return new Promise(resolve=>auth.onAuthStateChanged(async u=>{if(!u)return location.replace("index.html");try{let a=await db.collection("admins").doc(u.uid).get(),s=await db.collection("students").doc(u.uid).get(),d=s.exists?s.data():{};if((a.exists&&a.data().active!==false)||d.role==="admin"||d.isAdmin===true){window.currentAdmin=u;resolve(true)}else{await auth.signOut();location.replace("index.html")}}catch(e){console.error(e);await auth.signOut();location.replace("index.html")}}))}
async function logout(){await auth.signOut();location.replace("index.html")}
function shellNav(active){let a=[['dashboard.html','Dashboard','🏠'],['courses.html','Courses','📚'],['chapters.html','Chapters','📖'],['topics.html','Topics','🧩'],['quiz.html','Quizzes','📝'],['questions.html','Questions','❓'],['notes.html','Notes','📄'],['ncert.html','NCERT','📘'],['pyq.html','PYQ','🎯'],['students.html','Students','👨‍🎓'],['purchases.html','Purchases','💳'],['notifications.html','Notifications','🔔'],['profile.html','Profile','👤'],['settings.html','Settings','⚙️']];return `<aside class="sidebar"><div class="brand"><img src="assets/logo.png"><b>mNEET-Pro<small>Admin Panel</small></b></div><nav>${a.map(x=>`<a class="${active===x[0]?'active':''}" href="${x[0]}">${x[2]} ${x[1]}</a>`).join('')}</nav><button class="logout" onclick="logout()">↪ Logout</button></aside>`}
function rows(el,arr,empty='No data found.'){el.innerHTML=arr.length?arr.join(''):`<tr><td colspan="20" class="empty">${empty}</td></tr>`}
