requireAdmin().then(init);
async function init(){
 const c=param('courseId'),h=param('chapterId'),t=param('topicId'),q=param('quizId'); let id=param('id');
 if(!c||!h||!t||!q){toast('Open a quiz first, then choose Question.','error');setTimeout(()=>go('quiz.html'),900);return;}
 $('#back').href='quiz-editor.html?'+new URLSearchParams({courseId:c,chapterId:h,topicId:t,id:q}).toString();
 const qref=()=>db.collection('courses').doc(c).collection('chapters').doc(h).collection('topics').doc(t).collection('quizzes').doc(q).collection('questions');
 if(id){const snap=await qref().doc(id).get();if(!snap.exists){toast('Question not found','error');return;}const x=snap.data();$('#question').value=x.question||'';$('#imageUrl').value=x.imageUrl||'';$('#o1').value=x.options?.['1']||'';$('#o2').value=x.options?.['2']||'';$('#o3').value=x.options?.['3']||'';$('#o4').value=x.options?.['4']||'';$('#correct').value=String(x.correctOption||1);$('#solution').value=x.solution||'';$('#ref').value=x.ncertReference||'';$('#order').value=x.order||1;}
 $('#form').onsubmit=async e=>{e.preventDefault();const btn=$('#form button[type=submit]')||$('#form button');btn.disabled=true;try{let url=$('#imageUrl').value.trim();if($('#image').files[0])url=await uploadFile($('#image').files[0],'questions/'+q);const question=$('#question').value.trim();const opts={'1':$('#o1').value.trim(),'2':$('#o2').value.trim(),'3':$('#o3').value.trim(),'4':$('#o4').value.trim()};if(!question&&!url)throw Error('Question text or an image is required.');if(Object.values(opts).some(v=>!v))throw Error('Fill all four options.');const data={question,imageUrl:url,options:opts,correctOption:Number($('#correct').value),solution:$('#solution').value.trim(),ncertReference:$('#ref').value.trim(),order:Number($('#order').value||1),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(id){await qref().doc(id).set(data,{merge:true});}else{const n=await qref().add({...data,createdAt:firebase.firestore.FieldValue.serverTimestamp()});id=n.id;await db.collection('courses').doc(c).collection('chapters').doc(h).collection('topics').doc(t).collection('quizzes').doc(q).set({questionCount:firebase.firestore.FieldValue.increment(1)},{merge:true});}toast('Question saved successfully','success');setTimeout(()=>go('quiz-editor.html',{courseId:c,chapterId:h,topicId:t,id:q}),650);}catch(err){toast(err.message||'Could not save question','error');}finally{btn.disabled=false;}};
}
