requireAdmin().then(init);
let cid='',hid='',tid='',id='';
function qref(c,h,t,q){return db.collection('courses').doc(c).collection('chapters').doc(h).collection('topics').doc(t).collection('quizzes').doc(q)}
async function init(){try{cid=param('courseId');hid=param('chapterId');tid=param('topicId');id=param('id');let cs=(await db.collection('courses').get()).docs;$('#course').innerHTML=cs.map(d=>`<option value="${d.id}">${esc(d.data().name||d.data().title)}</option>`).join('');$('#course').onchange=loadH;if(cid){$('#course').value=cid;await loadH()}if(hid){$('#chapter').value=hid;await loadT()}if(tid)$('#topic').value=tid;if(id){let d=await qref(cid,hid,tid,id).get();if(d.exists){let x=d.data();$('#title').value=x.title||x.name||'';$('#type').value=x.type||'topic';$('#time').value=x.perQuestionTime||60}}$('#form').onsubmit=save;$('#add').onclick=()=>id?go('questions.html',{courseId:cid,chapterId:hid,topicId:tid,quizId:id}):toast('Save quiz first','error');if(id)loadQ()}catch(e){toast(e.message,'error')}}
async function loadH(){let c=$('#course').value,s=await db.collection('courses').doc(c).collection('chapters').get();$('#chapter').innerHTML=s.docs.map(d=>`<option value="${d.id}">${esc(d.data().name||d.data().title)}</option>`).join('');$('#topic').innerHTML='';if(hid&&c===cid)$('#chapter').value=hid;await loadT()}
async function loadT(){let c=$('#course').value,h=$('#chapter').value;if(!c||!h)return;let s=await db.collection('courses').doc(c).collection('chapters').doc(h).collection('topics').get();$('#topic').innerHTML=s.docs.map(d=>`<option value="${d.id}">${esc(d.data().name||d.data().title)}</option>`).join('');if(tid)$('#topic').value=tid}
async function save(e){e.preventDefault();let c=$('#course').value,h=$('#chapter').value,t=$('#topic').value;if(!c||!h||!t)return toast('Select course, chapter and topic','error');let ref=db.collection('courses').doc(c).collection('chapters').doc(h).collection('topics').doc(t).collection('quizzes'),d={title:$('#title').value.trim(),type:$('#type').value,perQuestionTime:Number($('#time').value||60),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!d.title)return toast('Quiz title is required','error');try{if(id)await ref.doc(id).set(d,{merge:true});else{let n=await ref.add({...d,questionCount:0,createdAt:firebase.firestore.FieldValue.serverTimestamp()});id=n.id;cid=c;hid=h;tid=t}toast('Quiz saved','success');history.replaceState({},'',`quiz-editor.html?courseId=${encodeURIComponent(c)}&chapterId=${encodeURIComponent(h)}&topicId=${encodeURIComponent(t)}&id=${encodeURIComponent(id)}`);$('#add').onclick=()=>go('questions.html',{courseId:c,chapterId:h,topicId:t,quizId:id});await loadQ()}catch(e){toast(e.message,'error')}}
async function loadQ(){let s=await qref(cid,hid,tid,id).collection('questions').get();rows($('#rows'),s.docs.map(d=>{let x=d.data();return `<tr><td>${x.order||0}</td><td>${esc((x.question||'Image question').slice(0,55))}</td><td>${x.correctOption||'—'}</td><td><button class="btn small" onclick="go('questions.html',{courseId:'${cid}',chapterId:'${hid}',topicId:'${tid}',quizId:'${id}',id:'${d.id}'})">Edit</button> <button class="btn small danger" onclick="removeQuestion('${d.id}')">Delete</button></td></tr>`}))}
async function removeQuestion(q){if(!await confirmDelete('Delete this question?'))return;try{await qref(cid,hid,tid,id).collection('questions').doc(q).delete();let n=(await qref(cid,hid,tid,id).collection('questions').get()).size;await qref(cid,hid,tid,id).set({questionCount:n},{merge:true});toast('Question deleted','success');loadQ()}catch(e){toast(e.message,'error')}}
